version: '3.4'

services:
  authservice:
    image: scottyjoe9/authservice
    build:
      context: ./AuthService/
      dockerfile: Dockerfile.debug
    ports:
    - "8081:80"
    volumes:
    - ./AuthService/bin/Debug/netcoreapp2.1/:/app
    container_name: AuthService